feat: improve error handling in mgmt-lambda
fingerprintjs/fingerprint-pro-cloudfront-integration pull request #180
Opened 2023-12-22 12:37 UTC by sshelomentsev

2023-12-22 12:50 UTC, necipallef approved these changes

2023-12-22 13:08 UTC, Orkuncakilkaya requested changes
left comments

2023-12-22 13:08 UTC, Orkuncakilkaya commented on mgmt-lambda/handlers/updateHandler.ts
> +    } else if (error.name === 'ResourceNotFoundException') {
Those 2 conditions looks duplicate to me. Am I missing something?

2023-12-22 13:23 UTC, sshelomentsev commented on mgmt-lambda/handlers/updateHandler.ts
> +    } else if (error.name === 'ResourceNotFoundException') {
yeah, fixed wrong exception name

2023-12-26 08:14 UTC, Orkuncakilkaya approved these changes

2023-12-26 08:23 UTC, TheUnderScorer approved these changes

2023-12-26 08:27 UTC, merged