CloudFront Integration v2
fingerprintjs/fingerprint-pro-cloudfront-integration pull request #195
Opened 2024-02-26 15:25 UTC by sshelomentsev

2024-02-26 18:09 UTC, ilfa commented on package.json
> +    "whatwg-fetch": "^3.6.20"
Do we still need it as we migrated to `node20`?

2024-02-26 18:09 UTC, ilfa commented on proxy/test/utils/customer-variables/selectors.test.ts
> +  // describe('from headers', () => {
Do we still need these tests?

2024-02-26 20:23 UTC, sshelomentsev commented on proxy/test/utils/customer-variables/selectors.test.ts
> +  // describe('from headers', () => {
Yes, updated

2024-02-26 20:23 UTC, sshelomentsev commented on package.json
> +    "whatwg-fetch": "^3.6.20"
no, removed

2024-02-28 11:01 UTC, necipallef requested changes

2024-02-28 11:01 UTC, necipallef commented on cloudformation/rules.guard
> +    Resources.FingerprintProCloudfrontLambdaVersion {
Is there a typo here or not? Cloudfront -> CloudFront

2024-02-28 11:01 UTC, necipallef commented on cloudformation/template.yml
> +              Fn::Sub: arn:aws:secretsmanager:us-east-1:${AWS::AccountId}:secret:${SecretName}-??????
Is this a mistake? Why do we prefer a hard-coded region value over a controlled one?

2024-02-28 11:01 UTC, necipallef commented on cloudformation/template.yml
> +  FingerprintProCloudfrontLambda:
Let's rename Cloudfront -> CloudFront with uppercase F for consistency

2024-02-28 11:01 UTC, necipallef commented on proxy/utils/log.ts
> +  process.env.AWS_LAMBDA_LOG_LEVEL = level
I could not find where this env variable is used. Could you point it out, please?

2024-02-28 11:01 UTC, necipallef commented on mgmt-lambda/test/handlers/handleStatus.test.ts
> +          Runtime: 'nodejs16.x',
should this be nodejs20?

2024-02-28 11:01 UTC, necipallef commented on proxy/test/utils/customer-variables/selectors.test.ts
> -  describe('from secrets manager and headers', () => {
we should consider deleting these codes if they are not needed anymore. They are in comment right now

2024-02-28 11:21 UTC, sshelomentsev commented on proxy/utils/log.ts
> +  process.env.AWS_LAMBDA_LOG_LEVEL = level
It used by Lambda runtime to determine log level for CloudWatch logs

2024-02-28 11:23 UTC, sshelomentsev commented on mgmt-lambda/test/handlers/handleStatus.test.ts
> +          Runtime: 'nodejs16.x',
It doesn't really matter. Here we check that LambdaClient was called from our handler

2024-02-28 11:26 UTC, sshelomentsev commented on cloudformation/template.yml
> +              Fn::Sub: arn:aws:secretsmanager:us-east-1:${AWS::AccountId}:secret:${SecretName}-??????
We require to have secret in us-east-1 for consistency with the deployed Lambda@Edge which must be in us-east-1 (CloudFront requirements)

2024-02-28 11:47 UTC, necipallef commented on mgmt-lambda/test/handlers/handleStatus.test.ts
> +          Runtime: 'nodejs16.x',
I know it doesn't affect the test result. I would be nice if we search for nodejsX in the project and only see nodejs20

2024-02-28 12:22 UTC, TheUnderScorer approved these changes

2024-02-28 14:09 UTC, sshelomentsev commented on proxy/test/utils/customer-variables/selectors.test.ts
> -  describe('from secrets manager and headers', () => {
I already updated these tests

2024-02-28 14:15 UTC, sshelomentsev commented on cloudformation/template.yml
> +  FingerprintProCloudfrontLambda:
fixed

2024-02-28 14:15 UTC, sshelomentsev commented on cloudformation/rules.guard
> +    Resources.FingerprintProCloudfrontLambdaVersion {
fixed

2024-02-28 14:32 UTC, necipallef approved these changes

2024-02-29 09:55 UTC, TheUnderScorer approved these changes

2024-02-29 12:28 UTC, merged

2024-02-29 12:31 UTC, ilfa commented
:tada: This PR is included in version 1.5.0-rc.1 :tada:

The release is available on:
- `v1.5.0-rc.1`
- [GitHub release](https://github.com/fingerprintjs/fingerprint-pro-cloudfront-integration/releases/tag/v1.5.0-rc.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-02-29 13:59 UTC, ilfa commented
:tada: This PR is included in version 2.0.0-rc.1 :tada:

The release is available on:
- `v2.0.0-rc.1`
- [GitHub release](https://github.com/fingerprintjs/fingerprint-pro-cloudfront-integration/releases/tag/v2.0.0-rc.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-03-01 16:47 UTC, ilfa commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- `v2.0.0`
- [GitHub release](https://github.com/fingerprintjs/fingerprint-pro-cloudfront-integration/releases/tag/v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: