ci: fix e2e tests for pnpm and node v20
fingerprintjs/fingerprint-pro-cloudfront-integration pull request #202
Opened 2024-03-01 00:02 UTC by sshelomentsev

2024-03-01 09:21 UTC, TheUnderScorer submitted a review, later dismissed

2024-03-01 09:31 UTC, ilfa requested changes
Can [pnpm workspaces](https://pnpm.io/workspaces#workspace-protocol-workspace) help us to simplify some steps?

2024-03-01 09:31 UTC, ilfa commented on .github/workflows/deploy_test_branch.yml
> +        run: npm i -g pnpm
Let`s use cache like we do in [dx-toolkit](https://github.com/fingerprintjs/dx-team-toolkit/blob/main/.github/workflows/build-typescript-project.yml#L63)

And also we can use github action `pnpm/action-setup` to install pnpm (but we should do it before installing node)

2024-03-01 11:32 UTC, sshelomentsev commented on .github/workflows/deploy_test_branch.yml
> +        run: npm i -g pnpm
fixed

2024-03-01 14:07 UTC, TheUnderScorer approved these changes

2024-03-01 14:08 UTC, merged

2024-03-01 16:47 UTC, ilfa commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- `v2.0.0`
- [GitHub release](https://github.com/fingerprintjs/fingerprint-pro-cloudfront-integration/releases/tag/v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-03-08 10:47 UTC, ilfa commented
:tada: This PR is included in version 2.0.0-rc.2 :tada:

The release is available on:
- `v2.0.0-rc.2`
- [GitHub release](https://github.com/fingerprintjs/fingerprint-pro-cloudfront-integration/releases/tag/v2.0.0-rc.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: